### ISSUE TITLE
Host incorrect in multi-cluster ingress recipe's diagram

### ISSUE THREAD

**Issue by muneebmaster** [GoogleCloudPlatform/gke-networking-recipes#18]
In this [diagram](https://github.com/GoogleCloudPlatform/gke-networking-recipes/blob/master/images/multi-cluster-ingress-external.png) for the [multi-cluster ingress recipe](https://github.com/GoogleCloudPlatform/gke-networking-recipes/tree/master/multi-cluster-ingress/multi-cluster-ingress-basic), both of the hosts are **foo.example.com** but the second one should be **bar.example.com**.

**Comment by theemadnes** [comment]
@mark-church ^^
