### ISSUE TITLE
Recipe for securing the default-backend with Cloud Armor

### ISSUE THREAD

**Issue by boredabdel** [GoogleCloudPlatform/gke-networking-recipes#25]
Consider an Ingress like this

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: foo-external
  namespace: foo
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: gke-foo
    networking.gke.io/managed-certificates: foo-ingress-cert
    kubernetes.io/ingress.allow-http: "false"
spec:
  rules:
  - host: foo.abdel.cloud
    http:
      paths:
      - path: /*
        backend:
          serviceName: foo
          servicePort: 8080

If the foo backend has a Cloud Armor  policy attached to it (to for example restrict which country/IP can talk to that specific backend) the default backend will not be behind the same policy.

This requires people to edit the l7-default-backend Service in the kube-system namespace and add a BackenConfig Annotation to it which points to the Cloud Armor Policy

We need to document this

**Comment by boredabdel** [comment]
@mikouaj is working on this

**Comment by mikouaj** [comment]
Looking into that :)

**Comment by mikouaj** [comment]
@boredabdel Cloud Armor enabled Ingress recipe was implemented and merged already, PR:
https://github.com/GoogleCloudPlatform/gke-networking-recipes/pull/51

**Comment by boredabdel** [comment]
True. Closing this one :)
