### ISSUE TITLE
mci with https from client to LB

### ISSUE THREAD

**Issue by boredabdel** [GoogleCloudPlatform/gke-networking-recipes#30]
Document an example of https MCI, this can be done with a tls secret or a Google Managed Certificate

https://cloud.google.com/kubernetes-engine/docs/how-to/multi-cluster-ingress#https_support
https://cloud.google.com/kubernetes-engine/docs/how-to/multi-cluster-ingress#google-managed_certificates

**Comment by theemadnes** [comment]
good idea - let's evaluate with Gateway API

**Comment by boredabdel** [comment]
Add this https://github.com/GoogleCloudPlatform/gke-networking-recipes/issues/31 into the same recipe

**Comment by boredabdel** [comment]
https://github.com/GoogleCloudPlatform/gke-networking-recipes/tree/master/ingress/multi-cluster/mci-frontend-config

Implemented with http to https redirect and google manager certs.
